secrets: private/secrets.yml
web_server:
  bind: 0.0.0.0
  port: 5050
api: yes
webui: yes

schedules:
# Run all tasks once an hour
  - tasks: '*'
    interval:
      hours: 1

templates:
  global:
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy
#        - \b3-?D\b: {from: title}
        - Blu-ray: {from: title}
        - BDRemux: {from: title}
        - полностью: {from: title}
        - MP4: {from: title}

  transmissionrpc:
    transmission:
      enabled: yes
      host: '{{ secrets.transmlogin.host }}'
      port: 9091
      username: '{{ secrets.transmlogin.usr }}'
      password: '{{ secrets.transmlogin.pwd }}'
      addpaused: no
      maxconnections: 30
    clean_transmission:
      enabled: no
      host: '{{ secrets.transmlogin.host }}'
      port: 9091
      username: '{{ secrets.transmlogin.usr }}'
      password: '{{ secrets.transmlogin.pwd }}'
      transmission_seed_limits: yes
 
  newdownload:
    email:
      from: '{{ secrets.emailset.addrfrom }}'
      to:
        - '{{ secrets.emailset.addrto }}'
      subject: "Добавлен новый торрент"
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_login: true
      smtp_username: '{{ secrets.emailset.smtpusr }}'
      smtp_password: '{{ secrets.emailset.smtppwd }}'
      smtp_tls: true
      template: html-downloaded.template

  tv:
    include: private/series.yml

  movies:
    quality: 1080p
    imdb_lookup: yes
    list_accept:
      - imdb_list:
          login: '{{ secrets.imdblogin.usr }}'
          password: '{{ secrets.imdblogin.pwd }}'
          list: watchlist
    set:
      path: '/volume1/Downloads/Films'
      content_filename: "{{ imdb_name|replace(' ', '.') }}"
      label: Films

tasks:
  lostfilm:
    priority: 1
    headers:
      cookie: '{{ secrets.lfc.uid }}'
    rss: http://www.lostfilm.tv/rssdd.xml
    urlrewrite:
      lostfilm:
        regexp: 'http://lostfilm.tv/download.php\?(?P<details>.*)'
        format: 'http://www.lostfilm.tv/download.php?\g<details>'
    template:
      - tv
      - newdownload
      - transmissionrpc
    manipulate:
      - title:
          replace:
            regexp: '[^a-zA-z0-9()]+\s'
            format: ''

  Movie:
    priority: 2
#    seen: local  # We don't want accepted movies on this feed to affect actual download feed
    inputs:
      - rss: '{{ secrets.nnmulrs.url1 }}'
      - rss: '{{ secrets.nnmulrs.url2 }}'
      - rss: '{{ secrets.nnmulrs.url4 }}'
    template:
      - movies
      - newdownload
      - transmissionrpc
    manipulate:
      - title:
          replace:
            regexp: '^[^\/]+\/\s'
            format: ''

  Want_download:
    priority: 3
    no_entries_ok: yes
    rss: '{{ secrets.nnmulrs.url3 }}'
    accept_all: yes
    download:
      path: /volume1/Downloads/tfiles/
      overwrite: yes
