variables: private/secretfile.yml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
# Run all tasks once an hour
#  - tasks: '*'
  - tasks: [lostfilm]
    interval:
      minutes: 30

templates:
  global:
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy: {from: title}
        - Blu-ray: {from: title}
        - BDRemux: {from: title}
        - Remux: {from: title}
        - AVO: {from: title}
        - PR: {from: title}
        - полностью: {from: title}
        - MP4: {from: title}

  torrents:
    transmission:
      enabled: yes
      host: '{? transmlogin.host ?}'
      port: 9091
      username: '{? transmlogin.usr ?}'
      password: '{? transmlogin.pwd ?}'
      add_paused: no
      max_connections: 30
      honor_limits: yes

#  movie-notify:
#    notify:
#      entries:
#        title: "Добавлен новый фильм: {{ imdb_name }}"
#        message: "{{ imdb_name }} [{{ quality }}]"
#        what: accepted
#        via:
#          - pushbullet:
#              url: "{% if imdb_url %}{{ imdb_url }}{% endif %}"
#              api_key: '{? pushbullet.apikey ?}'
  tg-notify:
    notify:
      entries:
        message: |+
           📥 Скачан сериал: {{ series_name }}. Сезон: {{ tvdb_season }}, Серия: {{tvdb_episode}}
           Будем смотреть? 😉
        via:
          - telegram:
              bot_token: '{? tgboot.bottoken ?}'
              parse_mode: markdown
              recipients:
                - chat_id: '{? tgboot.chtID ?}'

  email-notify:
    notify:
      task:
        title: "Добавлен новый торрент"
        template: html-downloaded.template
        via:
          - email:
              from: '{? emailset.addrfrom ?}'
              to:
                - '{? emailset.addrto ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? emailset.smtpusr ?}'
              smtp_password: '{? emailset.smtppwd ?}'
              smtp_tls: true
              html: yes

  tv:
    thetvdb_lookup: yes
    include: private/series.yml

  movies:
    regexp:
      reject:
        - WEB-DL: {from: title}
        - Line: {from: title}
#      accept:
#        - BDRip: {from: title}
    quality: 1080p h264
    content_size:
      min: 9000
    imdb_lookup: yes
#    list_match:
#      from:
#        - imdb_list:
#            login: '{? imdblogin.usr ?}'
#            password: '{? imdblogin.pwd ?}'
#            list: watchlist
    imdb_watchlist:
      user_id: ur66868441
      list: watchlist
    set:
      path: '/volume1/Downloads/Films'
      content_filename: "{{ imdb_name|replace(' ', '.') }}"
      label: Films

tasks:
  lostfilm:
    priority: 1
#    proxy: http://168.235.88.16:8080
    headers:
      cookie: '{? lfcn2.uid ?}'
    rss:
      url: http://insearch.site/rssdd.xml
      ascii: yes
    urlrewrite:
      lostfilm:
        regexp: 'https://lostfilm.tv/download.php\?(?P<details>.*)'
        format: 'https://www.lostfilm.tv/download.php?\g<details>'
    template: [tv, torrents, email-notify, tg-notify]
    manipulate:
      - title:
          replace:
            regexp: '[^a-zA-z0-9()]+\s'
            format: ''

  Movies1080p:
    priority: 3
    inputs:
      - rss: '{? RRSUrls.url1 ?}'
      - rss: '{? RRSUrls.url2 ?}'
    template: [movies, torrents, movie-notify, email-notify]
    manipulate:
      - title:
          replace:
            regexp: '^[^\/]+\/\s'
            format: ''

  Want_download:
    priority: 4
    no_entries_ok: yes
    rss: '{? RRSUrls.url3 ?}'
    accept_all: yes
    download:
#      path: /volume1/Downloads/tfiles/
      overwrite: yes
