variables: private/secretfile.yml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
# Run all tasks once an hour
  - tasks: '*'
    interval:
      minutes: 30

templates:
  global:
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy: {from: title}
#        - \b3-?D\b: {from: title}
        - Blu-ray: {from: title}
        - BDRemux: {from: title}
        - Remux: {from: title}
        - AVO: {from: title}
        - PR: {from: title}
        - полностью: {from: title}
        - MP4: {from: title}

  torrents:
    transmission:
      enabled: yes
      host: '{? transmlogin.host ?}'
      port: 9091
      username: '{? transmlogin.usr ?}'
      password: '{? transmlogin.pwd ?}'
      add_paused: no
      max_connections: 30
      honor_limits: yes
 
  series-notify:
    notify:
      entries:
        title: "Добавлена новая серия сериала: {{ tvdb_series_name }}"
        message: "{{ tvdb_series_name|default(series_name) }} - {{ tvdb_ep_name }}{% if tvdb_ep_name|default(False) %}{% endif %} - {{ tvdb_ep_id }} [{{ quality }}]"
        what: accepted
        via:
          - pushbullet:
              url: "{% if tvdb_url %}{{ tvdb_url }}{% endif %}"
              api_key: '{? pushbullet.apikey ?}'

  movie-notify:
    notify:
      entries:
        title: "Добавлен новый фильм: {{ imdb_name }}"
        message: "{{ imdb_name }} [{{ quality }}]"
        what: accepted
        via:
          - pushbullet:
              url: "{% if imdb_url %}{{ imdb_url }}{% endif %}"
              api_key: '{? pushbullet.apikey ?}'

  email-notify:
    notify:
      task:
        title: "Добавлен новый торрент"
        template: html-downloaded.template
#        what: accepted
        via:
          - email:
              from: '{? emailset.addrfrom ?}'
              to:
                - '{? emailset.addrto ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? emailset.smtpusr ?}'
              smtp_password: '{? emailset.smtppwd ?}'
              smtp_tls: true
              html: yes

  tv:
    thetvdb_lookup: yes
    include: private/series.yml

  movies:
    regexp:
      reject:
        - WEB-DL: {from: title}
        - Line: {from: title}
#      accept:
#        - BDRip: {from: title}
    quality: 1080p h264
    content_size:
      min: 10000
    imdb_lookup: yes
#    list_match:
#      from:
#        - imdb_list:
#            login: '{? imdblogin.usr ?}'
#            password: '{? imdblogin.pwd ?}'
#            list: watchlist
    imdb_watchlist:
      user_id: urXXXXXXXX
      list: watchlist
    set:
      path: '/volume2/Downloads/Films'
      content_filename: "{{ imdb_name|replace(' ', '.') }}"
      label: Films

tasks:
  lostfilm:
    priority: 1
    headers:
      cookie: '{? lfcn.uid ?}'
#    rss: https://old.lostfilm.tv/rssdd.xml
    lostfilm: yes
    urlrewrite:
      lostfilm:
        regexp: 'http://lostfilm.tv/download.php\?(?P<details>.*)'
        format: 'http://www.lostfilm.tv/download.php?\g<details>'
    template: [tv, torrents, series-notify, email-notify]
    manipulate:
      - title:
          replace:
            regexp: '[^a-zA-z0-9()]+\s'
            format: ''

  Movies1080p:
    priority: 3
#    proxy: http://200.146.245.53:8080
    inputs:
      - rss: '{? RRSUrls.url1 ?}'
      - rss: '{? RRSUrls.url2 ?}'
    template: [movies, torrents, movie-notify, email-notify]
    manipulate:
      - title:
          replace:
            regexp: '^[^\/]+\/\s'
            format: ''

  Want_download:
    priority: 4
#    proxy: http://200.146.245.53:8080
    no_entries_ok: yes
    rss: '{? RRSUrls.url3 ?}'
    accept_all: yes
    download:
      path: /volume2/Downloads/tfiles/
      overwrite: yes